/*
===============================================================================
DML Script: Magnitude Analysis
===============================================================================
Script Purpose:
    This script performs magnitude analysis in the Gold layer of the data 
		warehouse. It provides insights into key business metrics such as total 
		customers, products, and revenue by various dimensions like country

Usage:
    - This script can be executed to retrieve key magnitude-related metrics
===============================================================================
*/

-- Find total customers by countries
SELECT 
country, COUNT(customer_key) AS total_customers 
FROM gold.dim_customers 
GROUP BY country 
ORDER BY total_customers DESC

-- Find total customers by genders
SELECT 
gender, COUNT(customer_key) AS total_customers 
FROM gold.dim_customers 
GROUP BY gender 
ORDER BY total_customers DESC

-- Find total products by categories
SELECT 
category, COUNT(product_key) AS total_products 
FROM gold.dim_products 
GROUP BY category 
ORDER BY total_products DESC

-- Average cost in each category
SELECT 
category, AVG(cost) AS total_products 
FROM gold.dim_products 
GROUP BY category 
ORDER BY total_products DESC

-- Total revenue of each category
SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f 
LEFT JOIN gold.dim_products p 
ON p.product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- Total Revenue generated by each customer
SELECT
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY 
c.customer_key, 
c.first_name, 
c.last_name
ORDER BY total_revenue DESC

-- Distribution of sold items across the countries
SELECT 
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales f 
LEFT JOIN gold.dim_customers c 
ON c.customer_key = f.customer_key
GROUP BY c.country
ORDER BY total_sold_items DESC